### ISSUE TITLE
Build system (waf) fails on Ubuntu Studio 20.10 (Groovy Gorilla)

### ISSUE THREAD

**Issue by jhenkins** [thunderox/triceratops#9]
Hello Nick,

After upgrading to Studio Groovy, the bundled version of waf (1.6.11) started breaking with the versions of Python that comes as standard. The Ardour project also uses waf, and I tested building Triceratops with that version (2.0.19). I am happy to report that Ticeratops builds fine with this newer version of waf on Groovy. If you would like to review my fix, I have created a pull request for you to have a look at.

Cheerio,
Jan Henkins

**Comment by thunderox** [comment]
Thanks for this :)

**Comment by jhenkins** [comment]
Thanks Nick! 

Recently I updated to Ubuntu Studio 21.04 (Hairy Hippo, what a name...), and Triceratops still compiles cleanly. I'll close this issue.
